# Generated by Django 3.0.7 on 2024-02-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_leavereportstaff_cancellation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='cancellation_status',
            field=models.BooleanField(default=True),
        ),
    ]
